config/routes.rb
Shoes::Application.routes.draw do

  root  'pages#welcome' 

  get    "/welcome",        to: 'pages#welcome'
  get    "/signup",         to: 'users#new'
  get    "/signin",         to: 'sessions#new'
  delete "/signout/:id",    to: 'sessions#destroy', as: 'signout'

  resources :sessions,      only: [:new, :create, :destroy]
  resources :users
  resources :products

  resources :sales,         only: [:index, :destroy]
  post   "/sales/:id",      to: 'sales#create', as: 'create_sale'

  resources :admins,        only: [:index, :destroy]
  post   "/admins/:id",     to: 'admins#create', as: 'create_admin'

end

app/views/admins/index.html.erb
<!-- 
  Display the list of users in admin/current user style, for use
  by system administrators.  This allows the admin to designate
  other users as admins, or to demote admins to standard user
  status.  
 -->

<h2>Admins</h2>

<a href='<%= users_path %>'>Back to All Users</a>

<%  if @admin_users.length > 0 %>
  <table class='table table-striped table-hover table-condensed'>
    <thead>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </thead>
    <tbody>
  <%  @admin_users.each{ | admin | %>
      <tr>
        <td><a href='<%= user_path(admin.id) %>'><%= admin.first_name + ' ' + admin.last_name %></a></td>
        <td><%= admin.email %></td>
        <td>
    <%  if admin?(@current_user)  %>
          <a href='<%= admin_path(admin.id) %>' data-method='delete'>Demote</a>
    <%  end   %>
        </td>
      </tr>
  <%  } %>
    </tbody>
  </table>
<%  else %>

  <p>None</p>

<%  end %>

<h2>Standard Users</h2>

<a href='<%= new_user_path %>'>Create New User</a>

<%  if @users.length > 0 %>
  <table class='table table-striped table-hover table-condensed'>
    <thead>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </thead>
    <tbody>
  <%  @users.each{ | user | %>
      <tr>
        <td><a href='<%= user_path(user.id) %>'><%= user.first_name + ' ' + user.last_name %></a></td>
        <td><%= user.email %></td>
        <td>
    <%  if admin?(@current_user)  %>
          <a href='<%= create_admin_path(user.id) %>' data-method='post'>Promote</a>
    <%  end   %>
        </td>
      </tr>
  <%  } %>
    </tbody>
  </table>

<%  else %>

  <p>None</p>

<%  end %>