config/routes.rb
Shoes::Application.routes.draw do

  root  'pages#welcome' 

  get    "/welcome",        to: 'pages#welcome'
  get    "/signup",         to: 'users#new'
  get    "/signin",         to: 'sessions#new'
  delete "/signout/:id",    to: 'sessions#destroy', as: 'signout'

  resources :sessions,      only: [:new, :create, :destroy]
  resources :users
  resources :products

  resources :sales,         only: [:index, :destroy]
  post   "/sales/:id",      to: 'sales#create', as: 'create_sale'

  resources :admins,        only: [:index, :destroy]
  post   "/admins/:id",     to: 'admins#create', as: 'create_admin'

end

app/models/user.rb
class User < ActiveRecord::Base

  #   User is the root data record/model for this system, and connects
  #   to all other records.  Specifically, the user id also functions
  #   as product.seller_id, sale.buyer_id, and admin.admin_user_id.
  
  #   Model validation includes ensuring the presence of first and
  #   last names, email and password, that email is valid, and that
  #   password matches password confirmation.  Names must be 50 chars
  #   or less, and passwords must be between 6 and 40 chars.
  
  #   Salt is created by authenticate() when creating a User record

  attr_accessor :password

  has_many  :products,  dependent:  :destroy, foreign_key: "seller_id"
  has_many  :sales,     dependent:  :destroy, foreign_key: "buyer_id"
  has_one   :admin,     dependent:  :destroy, foreign_key: "admin_user_id"

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name,  :presence => true,
            :length                 => { maximum: 50 }
  validates :last_name,   :presence => true,
            :length                 => { maximum: 50 }
  validates :email,   :presence     => true,
            :format                 => { with: email_regex },
            :uniqueness             => { case_sensitive: false }

  validates :password,  :presence   => true,
            :confirmation           => true,
            :length                 => { within: 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end


  # class method that checks whether the user's email and submitted_password are valid
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end


  private
    def encrypt_password
      # generate a unique salt if it's a new user
      self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
    
      # encrypt the password and store that in the encrypted_password field
      self.encrypted_password = encrypt(password)
    end

    # encrypt the password using both the salt and the passed password
    def encrypt(pass)
      Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #   Manages the creation and update of user registrations.
  #   - Creating an acct uses :new and :create.  
  #   - Viewing the users list uses :index.
  #   - Viewing a user dashboard uses :show.
  #   - Editing a user profile uses :edit and :update.
  #  
  #   Admin access is required for the remaining RESTful 
  #   CRUD functionality (:destroy, which removes a user).
  #   
  #   Except when creating a new user account, the user must
  #   be signed in when using these functions.  As mentioned
  #   above, user must be Admin to use :destroy.
  # 
  #   Unlike a Session, a User object IS backed by a model.  
  #
  #   SessionsHelper provides numerous companion functions to
  #   track current user, creating a User subset that can be 
  #   passed to views (i.e. without password). Also contains
  #   functions to check whether signed-in, whether admin, 
  #   or whether user "owns" user-specific views requested. 

  before_action :require_signin, except: [:new, :create]
  before_action :require_user_exists, only: [:show, :edit, :update, :destroy]

  def index
    current_user

    @users = User.includes(:admin).select(:id, :first_name, :last_name, :email, :created_at).all
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if !user.save      
      user.errors.full_messages.each_index{ |idx| flash["error-#{idx}"] = "#{user.errors.full_messages[idx]}" }
      
      redirect_to new_user_path, error: "User could not be created."
    else
      if (signed_in? && admin?(current_user))
        redirect_to users_path, notice: "User was successfully created."
      else
        @user = User.select(:id, :first_name, :last_name, :email, :created_at).find(user.id)
        sign_in @user
        redirect_to user_path(@user.id), notice: "Your account was successfully created."
      end
    end
  end

  def show

    if !user_exists?(params[:id])
      deny_user_not_found
    else
      @user = User.select(:id, :first_name, :last_name, :email, :created_at).find(params[:id])
      current_user
      
      @offers = Product.get_offers_by_user(@user.id)
      @offers_sum = "$%6.2f" % @offers.reduce(0){|sum, offer| sum + offer.amount }


      @sales = Sale.get_sales_by_user(@user.id)
      @sales_sum = "$%6.2f" % @sales.reduce(0){|sum, sale| sum + sale.prod_amt }
      
      @purchases = Product.get_purchases_by_user(@user.id)
      @purch_sum = "$%6.2f" % @purchases.reduce(0){|sum, purchase| sum + purchase.prod_amt }
    end
  end

  def edit
    if !signed_in? 
      deny_not_signed_in
    elsif !user_exists?(params[:id])
      deny_user_not_found
    end

    @user = User.select(:id, :first_name, :last_name, :email, :created_at).find(params[:id])
    if !current_user?(@user) && !admin?(current_user)
      deny_wrong_user
    end

  end

  def update
    user = User.find(params[:id])
    if user.update(user_params) == false      
      user.errors.full_messages.each_index{ |idx| flash["error-#{idx}"] = "#{user.errors.full_messages[idx]}" }
      redirect_to edit_user_path(user.id), error: "User could not be updated."
    else
      redirect_to user_path(user.id), notice: "User was successfully updated."
    end
    
  end

  def destroy
    user = User.find(params[:id])
    
    if current_user?(user)
      flash[:error] = "You really shouldn't delete yourself - it isn't healthy!"
    elsif user.destroy == false
      user.errors.full_messages.each_index{ |idx| flash["error-#{idx}"] = "#{user.errors.full_messages[idx]}" }
    end

    redirect_to users_path
  end


  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/views/users/edit.html.erb
<!-- 
  simple_form view to edit a user's profile. 
  Password and confirmation are both required with each edit,
  which is something I should separate out in the future.
 -->
 
<h2>Change User Profile</h2>

<%= simple_form_for(@user, html: {class: 'form-vertical' }) do |f| %>
  <%= f.input :first_name, autofocus: true %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :password, placeholder: 'password required' %>
  <%= f.input :password_confirmation  %>
  <%= f.button :submit, 'Save', class: 'btn-primary form-button' %>
  <div>
    <%= link_to "Return to previous view", user_path(@user.id) %>
  </div>
<% end %>

app/views/users/index.html.erb
<!-- 
  Display the list of all users - name, email, and link to dashboard.
  Also, for the current user only, a link to edit their profile.   
  
  If the current user is an admin, present per-user links to promote
  the user to administrator status (or demote the admin user!) or to
  delete this user from the system.  Also, show a link to display 
  users in 'admin-status' format, and to create a new user record
  while remaining signed in as an administrator.  

  The 'Delete User' link invokes a modal dialog, to confirm that
  this is really the user's intent.  This same dialog is used when 
  deleting a product or a successful purchase.  

  An interesting future feature might be to indicate in this list 
  which users are currently signed in - basically Sessions#index.
 -->

<h2>All Users</h2>

<%  if admin?(@current_user)  %>
  <a href='<%= admins_path %>'>Admins List</a> | 
  <a href='<%= new_user_path %>'>Create New User</a>
<%  end  %>

<%  if @users.length > 0 %>
  <table class='table table-striped table-hover table-condensed'>
    <thead>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    <%  if admin?(@current_user)  %>
      <th>Type</th>
      <th>Admin Actions</th>
    <%  end   %>
    </thead>
    <tbody>
    <%  @users.each{ | user | %>
      <tr>
        <td><a href='<%= user_path(user.id) %>'><%= user.first_name + ' ' + user.last_name %></td>
        <td><%= user.email %></td>
        <td>
      <%  if current_user?(user)  %>
          <a href='<%= edit_user_path(user.id) %>'>Edit Profile</a>
      <%  end   %>
        </td>
      <%  if admin?(@current_user)  %>
        <% if admin?(user) %>
            <td>Admin</td>
            <td><a href='<%= admin_path(user.id) %>' data-method='delete'>Demote</a>
        <% else %>
            <td>User</td>
            <td><a href='<%= admin_path(user.id) %>' data-method='post'>Promote</a>
        <% end %>
              |
              <a data-toggle='modal' href='#deleteModal' user-id='<%= user.id %>' class='delete-user'>
              Delete User</a>
            </td>
      <%  end   %>
      </tr>
    <%  } %>
    </tbody>
  </table>
<%  else %>
  <p>None</p>
<%  end %>

app/views/users/new.html.erb
<!-- 
  simple_form view to create a new user. 
 -->
 
<h2>New User</h2>

<%=   simple_form_for(@user, html: {class: 'form-horizontal' }) do |f|  %>

  <%=   f.input :first_name, autofocus: true  %>
  <%=   f.input :last_name  %>
  <%=   f.input :email      %>
  <%=   f.input :password   %>
  <%=   f.input :password_confirmation  %>
  <%=   f.button :submit, 'Sign Up', class: 'btn-primary form-button'  %>

<%  end   %>

app/views/users/show.html.erb
<!-- 
  Display a user's dashboard - each product they are offering,
  each sale they have made, and each purchase they have made.  
  Also, show the total dollar amount of the offers, sales and
  purchases.  Finally, provide links to edit or remove an offer,
  cancel a sale or cancel a purchase (these 'cancel' links are
  a bit questionable in the real-world, but are presented to
  demonstrate technical understanding).   
  
  Note that all dashboards are open for viewing by all users.  
  So, only show the edit/remove product links if this is OUR
  dashboard, or if we are an admin.  Also, only show 'cancel' 
  links if we are the current user, or if we are admin, or if
  we are the OTHER side of a settled purchase/sale.  

  The 'Remove Product', 'Cancel Sale' and 'Cancel Purchase'
  links are defended by a modal dialog, to confirm that this 
  is really the user's intent.  It is the same dialog as
  used when an admin deletes a user account.  
 -->
 
<h2><%= @user.first_name %>'s Dashboard</h2>

<%  if current_user?(@user)  %>
  <a href='<%= new_product_path %>'>Sell a Product</a>
<%  end  %>

<h3><%= @user.first_name %>'s products for sale:</h3>
<%  if @offers.length > 0 %>
  <table class='table table-striped table-hover table-condensed'>
    <thead>
      <th>Product</th>
      <th>Posted</th>
      <th>Amount</th>
    <%  if admin?(@current_user) || current_user?(@user)  %>
      <th>Action</th>
    <%  end  %>
    </thead>
    <tbody>
  <%  @offers.each{|offer| %>
      <tr>
        <td><a href='<%= product_path(offer.id) %>'><%= offer.name %></a></td>
        <td><%= l(offer.created_at, format: :notime) %></td>
        <td><%= "$%6.2f" % offer.amount %></td>
    <%  if admin?(@current_user) || current_user?(@user)  %>
        <td>
          <a href='<%= edit_product_path(offer.id) %>'>Edit Product</a>
           | 
          <a data-toggle='modal' href='#deleteModal' product-id='<%= offer.id %>' class='delete-product'>Remove Product</a>
        </td>
    <%  end  %>
      </tr>
  <%  }   %>
    </tbody>
  </table>

  <p class='text-right'>
    Total value of items: <strong><%= @offers_sum %></strong>
  </p>
<%  else %>
  <p>None</p>
<%  end   %>

<h3><%= @user.first_name %>'s products already sold:</h3>
<%  if @sales.length > 0 %>
  <table class='table table-striped table-hover table-condensed'>
    <thead>
      <th>Product</th>
      <th>Posted</th>
      <th>Bought</th>
      <th>Buyer</th>
      <th>Amount</th>
      <th>Action</th>
    </thead>
    <tbody>
  <%  @sales.each{ |sale| %>
      <tr>
        <td><a href='<%= product_path(sale.prod_id) %>'><%= sale.prod_name %></a></td>
        <td><%= l(sale.post_date.to_time, format: :notime) %></td>
        <td><%= l(sale.sale_date.to_time, format: :notime) %></td>
        <td><a href='<%= user_path(sale.buyer_id) %>'><%= sale.buyer_name %></a></td>
        <td><%= "$%6.2f" % sale.prod_amt %></td>
        <td>
    <%  if admin?(@current_user) || current_user?(@user) || (@current_user.id == sale.buyer_id) %>
          <a data-toggle='modal' href='#deleteModal' sale-id='<%= sale.id %>' class='delete-sale'>Cancel Sale</a>
    <%  end  %>
        </td>
      </tr>
  <%  }   %>
    </tbody>
  </table>

  <p class='text-right'>
    Total amount sold: <strong><%= @sales_sum %></strong>
  </p>
<%  else %>
  <p>None</p>
<%  end   %>

<h3><%= @user.first_name %>'s purchases:</h3>
<%  if @purchases.length > 0 %>
  <table class='table table-striped table-hover table-condensed'>
    <thead>
      <th>Product</th>
      <th>Seller</th>
      <th>Posted</th>
      <th>Bought</th>
      <th>Amount</th>
      <th>Action</th>
    </thead>
    <tbody>
  <%  @purchases.each{|purchase| %>
      <tr>
        <td><a href='<%= product_path(purchase.prod_id) %>'><%= purchase.prod_name %></a></td>
        <td><a href='<%= user_path(purchase.seller_id) %>'><%= purchase.seller_name %></a></td>
        <td><%= l(purchase.post_date.to_time, format: :notime) %></td>
        <td><%= l(purchase.sale_date.to_time, format: :notime) %></td>
        <td><%= "$%6.2f" % purchase.prod_amt %></td>
        <td>
    <%  if admin?(@current_user) || current_user?(@user) || (@current_user.id == purchase.seller_id) %>
          <a data-toggle='modal' href='#deleteModal' sale-id='<%= purchase.sale_id %>' class='delete-purchase'>Cancel Purchase</a>
    <%  end  %>
        </td>
      </tr>
  <%  }   %>
    </tbody>
  </table>

  <p class='text-right'>
    Total amount spent: <strong><%= @purch_sum %></strong>
  </p>
<%  else %>
  <p>None</p>
<%  end   %>