config/routes.rb
Shoes::Application.routes.draw do

  root  'pages#welcome' 

  get    "/welcome",        to: 'pages#welcome'
  get    "/signup",         to: 'users#new'
  get    "/signin",         to: 'sessions#new'
  delete "/signout/:id",    to: 'sessions#destroy', as: 'signout'

  resources :sessions,      only: [:new, :create, :destroy]
  resources :users
  resources :products

  resources :sales,         only: [:index, :destroy]
  post   "/sales/:id",      to: 'sales#create', as: 'create_sale'

  resources :admins,        only: [:index, :destroy]
  post   "/admins/:id",     to: 'admins#create', as: 'create_admin'

end

app/models/product.rb
class Product < ActiveRecord::Base

  #   Product is the data record/model for an item offered for sale.
  #   As such, it has a many-one relationship with User.  That is,
  #   an user can have many products for sale.  

  #   Seller_id binds the record to the user that is offering it. 
  #   Name, amount and description round out the offering.

  #   Basic validation ensures name, amount and seller_id are set,
  #   and that amount is non-negative.

  belongs_to :seller,    class_name: "User"
  has_one    :sale,      dependent:  :destroy

  validates  :name,      presence: true
  validates  :amount,    presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates  :seller_id, presence: true

  class << self

    def get_purchases_by_user(purchaser_id)
      my_purchases = joins(:seller, :sale).
                     where("sales.buyer_id = ?", purchaser_id).
                     select("products.amount AS prod_amt, products.created_at AS post_date, products.id AS prod_id, products.name AS prod_name, sales.created_at AS sale_date, sales.id AS sale_id, seller_id, users.first_name || ' ' || users.last_name AS seller_name").
                     order(:id)
    end

    def get_offers_by_user(offerer_id)
      my_offers = includes(:sale).
                  where(seller_id: offerer_id).
                  where(sales: {product_id: nil}).
                  order(:id)
    end

    def get_product_by_id(product_id)
      product = joins(:seller).
                select("products.amount, products.created_at, products.description, products.id, products.name AS prod_name, seller_id, users.first_name || ' ' || users.last_name AS seller_name").
                find(product_id)
    end

  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  #   RESTful CRUD functionality, requiring a signed-in user.
  #   Used to create/edit/remove a product offering, and to 
  #   show the list of offerings.

  include ProductsHelper

  before_action :require_signin
  before_action :require_product_exists, only: [:show, :edit, :update, :destroy]

  def index
    @avail_products = Product.includes(:sale, :seller).where(sales: {product_id: nil})
    @prod_sum = "$%6.2f" % @avail_products.reduce(0){ |sum, purchase| sum+purchase.amount }
  end

  def new
    @product = Product.new(seller_id: current_user.id)
  end

  def show
    @product = Product.get_product_by_id(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    require_current_user(@product.seller)
  end

  def create
    product = Product.new(product_params)

    if !product.save      
      product.errors.full_messages.each_index{ |idx| flash["error-#{idx}"] = "#{product.errors.full_messages[idx]}" }
      redirect_to new_product_path, error: "Product could not be created."
    else
      redirect_to user_path(product.seller_id), notice: "Product was successfully created."
    end
  end

  def update
    product = Product.find(params[:id])

    if !current_user?(product.seller) && !admin?(current_user)
      redirect_to user_path(product.seller_id), error: "You cannot edit product listings that are not yours."
    elsif product.update(product_params) == false      
      product.errors.full_messages.each_index{ |idx| flash["error-#{idx}"] = "#{product.errors.full_messages[idx]}" }
      redirect_to edit_product_path(product.id), error: "Product could not be updated."
    else
      redirect_to user_path(product.seller_id), notice: "Product was successfully updated."
    end
  end

  def destroy
    product = Product.find(params[:id])
    
    if !current_user?(product.seller) && !admin?(current_user)
      flash[:error] = "You cannot remove product listings that are not yours."
    elsif product.destroy == false
      product.errors.full_messages.each_index{ |idx| flash["error-#{idx}"] = "#{product.errors.full_messages[idx]}" }
    else
      flash[:notice] = "Product was successfully removed."
    end

    redirect_to user_path(product.seller_id)
  end


  private
  def product_params
    params.require(:product).permit(:name, :amount, :seller_id, :description)
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  #   ProductsHelper provides validation functions for whether
  #   a product with the given ID exists.   
  #   I've moved them here, out of ProductsController, since 
  #   they do not 'catch URLs' like controller methods do.


  #   Does the passed-in product exist?
  def product_exists?(product_id)
    Product.where(id: product_id).length > 0
  end

  #   Handle cases where this product_id does not exist.
  def deny_product_not_found
    flash[:error] = "Product not found."
    redirect_to products_path
  end

  #   Redirect to products if this product_id doesn't exist.
  def require_product_exists
    deny_product_not_found unless product_exists?(params[:id])
  end

end

app/views/products/edit.html.erb
<!-- 
  simple_form view to edit product details. 
 -->

<h3>Edit Product Details: ID <%= @product.id %></h3>

<%= link_to "Back to All Products", products_path %>

<%= simple_form_for(@product, html: {class: 'form-vertical' }) do |f| %>
  <%= f.input :name, autofocus: true %>
  <%= f.input :amount, input_html: {value: number_with_precision(f.object.amount, precision: 2) } %>
  <%= f.input :description, as: :text, input_html: { class: 'form-control', rows: 4 }  %>
  <%= f.hidden_field :seller_id %>
  <%= f.button :submit, 'Update', class: 'btn-primary form-button' %>
  <div>
    <%= link_to "Return to previous view", products_path %>
  </div>
<% end %>

app/views/products/index.html.erb
<!-- 
  Display the list of all product offerings - name, seller, post date,
  amount, and more details.  Also, for each item where the current 
  user is the seller, show a link to edit or remove the product.   
  
  If current user is admin, the seller links are always presented.
  This could be used to purge objectionable items from the system.  

  The 'Remove Product' link invokes a modal dialog, to confirm that
  this is really the user's intent.  This same dialog is used if 
  deleting successful purchases/sales (or if admins delete users).  
 -->

 <h2>All Products</h2>

<a href='<%= new_product_path %>'>Sell a Product</a>

<h3>Products For Sale</h3>

<%  if @avail_products.length > 0 %>
  <table class='table table-striped table-hover table-condensed'>
    <thead>
      <th>Product</th>
      <th>Seller</th>
      <th>Posted</th>
      <th>Amount</th>
      <th>Action</th>
    </thead>
    <tbody>

  <%    @avail_products.each{ | product | %>
      <tr>
        <td><a href='<%= product_path(product.id) %>'><%= product.name %></a></td>
        <td><a href='<%= user_path(product.seller.id) %>'><%= product.seller.first_name + ' ' + product.seller.last_name %></a></td>
        <td><%= l(product.created_at, format: :notime) %></td>
        <td><%= "$%6.2f" % product.amount %></td>
        <td>
          <a href='<%= create_sale_path(product.id) %>' data-method='post'>Buy</a>
    <%  if admin?(@current_user) || (@current_user.id == product.seller.id)   %>
           | 
          <a href='<%= edit_product_path(product.id) %>'>Edit</a>
           | 
          <a data-toggle='modal' href='#deleteModal' product-id='<%= product.id %>' class='delete-product'>Remove</a>
    <%  end   %>
        </td>
      </tr>
  <%    } %>
    
    </tbody>
  </table>

  <p class='text-right'>
    Total value of these offerings: <strong><%= @prod_sum %></strong>
  </p>

<% else %>

  <p>None</p>

<%  end %>

app/views/products/new.html.erb
<!-- 
  simple_form view to create a new product for sale. 
 -->
 
<h2>Register a Product For Sale</h2>

<%= link_to "Back to All Products", products_path %>

<%=   simple_form_for(@product, html: {class: 'form-horizontal' }) do |f|  %>
  <%= f.input :name, autofocus: true  %>
  <%= f.input :amount  %>
  <%= f.input :description, as: :text, input_html: { class: 'form-control', rows: 4 }  %>
  <%= f.hidden_field :seller_id %>
  <%= f.button :submit, 'Sell', class: 'btn-primary form-button'  %>
<%  end   %>

app/views/products/show.html.erb
<!-- 
  Display details about an item for sale - name, amount, seller,
  description, and links to Buy the item.  Note that all items 
  are open for viewing by all users. 

  Also if the current user is the seller (or an admin), present
  links to edit or remove the item.   
  
  The 'Remove Product'  link is defended by a modal dialog, to 
  confirm that this is really the user's intent.  It is the same
  dialog as used when deleting a sale/purchase (or when an admin 
  removes a user).  
 -->

<h2>Product Details: ID <%= @product.id %></h2>

<table class='table table-striped table-hover table-condensed'>
  <thead>
    <th>Name</th>
    <th>Posted</th>
    <th>Amount</th>
    <th>Seller</th>
    <th>Action</th>   <!-- Actions -->
  </thead>
  <tbody>
    <tr>
      <td><%= @product.prod_name %></td>
      <td><%= l(@product.created_at, format: :notime) %></td>
      <td><%= "$%6.2f" % @product.amount %></td>
      <td><a href='<%= user_path(@product.seller_id) %>'><%= @product.seller_name %></a></td>
      <td>
<%  if !@product.sale   %>
        <a href='<%= create_sale_path(@product.id) %>' data-method='post'>Buy</a>
<%  end   %>
<%  if admin?(@current_user) || (@current_user.id == @product.seller_id)   %>
  <%  if !@product.sale   %>
         | 
  <%  end   %>
        <a href='<%= edit_product_path(@product.id) %>'>Edit</a>
         | 
        <a data-toggle='modal' href='#deleteModal' product-id='<%= @product.id %>' class='delete-product'>Remove</a>
<%  end   %>
      </td>
    </tr>
  </tbody>
</table>

<p><%= @product.description %></td></p>