config/routes.rb
Shoes::Application.routes.draw do

  root  'pages#welcome' 

  get    "/welcome",        to: 'pages#welcome'
  get    "/signup",         to: 'users#new'
  get    "/signin",         to: 'sessions#new'
  delete "/signout/:id",    to: 'sessions#destroy', as: 'signout'

  resources :sessions,      only: [:new, :create, :destroy]
  resources :users
  resources :products

  resources :sales,         only: [:index, :destroy]
  post   "/sales/:id",      to: 'sales#create', as: 'create_sale'

  resources :admins,        only: [:index, :destroy]
  post   "/admins/:id",     to: 'admins#create', as: 'create_admin'

end

app/views/layouts/_delete_modal.html.erb
<!-- 
  This is the modal dialog that is used when deleting records - 
  users, products, sales.  Because so much code is common
  between these cases, a click handler catches which type of 
  deletion, and customizes the action and certain dialog text.  
  This is a standard Bootstrap modal.   
 -->

<script type="text/javascript">
  $(document).ready(function()
  { 
    $('body').on('click', '.delete-user', function()
    {
      var user_id = $(this).attr('user-id');
      $('.modal-header .modal-title').html("Remove a User");
      $('#modal-action-btn').val("Remove the User");
      $('#modal-form').attr('action', '/users/' + user_id);
    });

    $('body').on('click', '.delete-product', function()
    {
      var product_id = $(this).attr('product-id');
      $('.modal-header .modal-title').html("Remove a Product");
      $('#modal-action-btn').val("Remove the Product");
      $('#modal-form').attr('action', '/products/' + product_id);
    });

    $('body').on('click', '.delete-sale', function()
    {
      var sale_id = $(this).attr('sale-id');
      $('.modal-header .modal-title').html("Cancel a Sale");
      $('#modal-action-btn').val("Cancel the Sale");
      $('#modal-form').attr('action', '/sales/' + sale_id);
    });
    
    $('body').on('click', '.delete-purchase', function()
    {
      var sale_id = $(this).attr('sale-id');
      $('.modal-header .modal-title').html("Cancel a Purchase");
      $('#modal-action-btn').val("Cancel the Purchase");
      $('#modal-form').attr('action', '/sales/' + sale_id);
    });
    
  }); 
</script>

<div class='modal fade' id='deleteModal' tabindex='-1' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
  <div class='modal-dialog'>
    <div class='modal-content'>
      <div class='modal-header'>
        <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
        <h4 class='modal-title'></h4>
      </div>
      <div class='modal-body'>
        <h4 class='modal-title'>Are you sure you want to do this?  This operation is not reversible.</h4>
      </div>
      <div class='modal-footer'>
        <form action='/' method='post' id='modal-form'>
          <a href='#' class='btn btn-success' data-dismiss='modal'>No Change</a>
          <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>' />
          <input name='_method' type='hidden' value='delete' />
          <input type='submit' class='btn btn-danger' id='modal-action-btn' value='' />
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>

<% flash.each do |name, msg| %>
  <%  if msg.is_a?(String) %>

    <%  if name.to_s == 'notice'  %>
      <div class="alert alert-success">
    <%  else  %>
      <div class="alert alert-danger">
    <%  end   %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      </div>

  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- 
  Nav bar accomodates sscreen sizes smaller than 768px
  across by collapsing into a 'burger' menu.  

  Also, the right-side content changes when users sign
  in, to offer 'Edit Profile' and 'Sign Out' instead of 
  'Sign Up' and 'Sign In'.    

  Similarly, the main nav links are pulled in from a
  navigation_links file - and are only shown if the 
  session is signed-in.    
 -->

<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Shoe Biz', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <p class="navbar-text pull-right">
<% if signed_in? %>
        Welcome <strong><%= current_user.first_name %></strong>!
         |
        <%= link_to 'Edit Profile', edit_user_path(current_user.id), class: 'navbar-link' %>
         |
        <%= link_to "Sign Out", session_path(current_user.id), method: :delete, :class => 'navbar-link'  %>
<% else %>
        <%= link_to "Sign Up", signup_path, :class => 'navbar-link'  %>
         |
        <%= link_to "Sign In", signin_path, class: 'navbar-link'  %>
<% end %>
      </p>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<!-- 
  Present these links in the navigation bar, so they
  are present at all times when a user is signed in.
  Most importantly the link to the user's dashboard,
  but also links to all products for sale, all 
  historical sales, and all user accounts.  
 -->

<%# add navigation links to this file %>

<% if signed_in? %>
  <li><%= link_to 'My Dashboard', user_path(@current_user.id) %></li>
  <li><%= link_to 'Products',     products_path %></li>
  <li><%= link_to 'Sales',        sales_path %></li>
  <li><%= link_to 'Users',        users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- 
  All views in this app use this same view template.
  It includes basic HTML5 setup, our css and js files,
  our authenticity token, and the built-in UI elements
  that are present in each page.

  These built-in elements include the navigation bar,
  any error/notice messages, and a modal dialog (to
  confirm deletions).  
 -->

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shoe Business" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blackbelt" %>">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  
  </head>
 
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
  
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= render 'layouts/delete_modal' %>
       <%= yield %>
    </main>
  
  </body>
</html>